package main

type ServiceGenerationInfo struct {
	FileNameWithoutExtension string
	ServiceName              string
}

var ServiceInfoMap = map[string]ServiceGenerationInfo{
	"MlflowService": {
		FileNameWithoutExtension: "tracking",
		ServiceName:              "TrackingService",
	},
	"ModelRegistryService": {
		FileNameWithoutExtension: "model_registry",
		ServiceName:              "ModelRegistryService",
	},
	"MlflowArtifactsService": {
		FileNameWithoutExtension: "artifacts",
		ServiceName:              "ArtifactsService",
	},
}

var ImplementedEndpoints = []string{
	"MlflowService_getExperimentByName",
	"MlflowService_createExperiment",
	// "MlflowService_searchExperiments",
	"MlflowService_getExperiment",
	"MlflowService_deleteExperiment",
	// "MlflowService_restoreExperiment",
	// "MlflowService_updateExperiment",
	"MlflowService_createRun",
	// "MlflowService_updateRun",
	// "MlflowService_deleteRun",
	// "MlflowService_restoreRun",
	// "MlflowService_logMetric",
	// "MlflowService_logParam",
	// "MlflowService_setExperimentTag",
	// "MlflowService_setTag",
	// "MlflowService_setTraceTag",
	// "MlflowService_deleteTraceTag",
	// "MlflowService_deleteTag",
	// "MlflowService_getRun",
	"MlflowService_searchRuns",
	// "MlflowService_listArtifacts",
	// "MlflowService_getMetricHistory",
	// "MlflowService_getMetricHistoryBulkInterval",
	"MlflowService_logBatch",
	// "MlflowService_logModel",
	// "MlflowService_logInputs",
	// "MlflowService_startTrace",
	// "MlflowService_endTrace",
	// "MlflowService_getTraceInfo",
	// "MlflowService_searchTraces",
	// "MlflowService_deleteTraces",
	// "ModelRegistryService_createRegisteredModel",
	// "ModelRegistryService_renameRegisteredModel",
	// "ModelRegistryService_updateRegisteredModel",
	// "ModelRegistryService_deleteRegisteredModel",
	// "ModelRegistryService_getRegisteredModel",
	// "ModelRegistryService_searchRegisteredModels",
	// "ModelRegistryService_getLatestVersions",
	// "ModelRegistryService_createModelVersion",
	// "ModelRegistryService_updateModelVersion",
	// "ModelRegistryService_transitionModelVersionStage",
	// "ModelRegistryService_deleteModelVersion",
	// "ModelRegistryService_getModelVersion",
	// "ModelRegistryService_searchModelVersions",
	// "ModelRegistryService_getModelVersionDownloadUri",
	// "ModelRegistryService_setRegisteredModelTag",
	// "ModelRegistryService_setModelVersionTag",
	// "ModelRegistryService_deleteRegisteredModelTag",
	// "ModelRegistryService_deleteModelVersionTag",
	// "ModelRegistryService_setRegisteredModelAlias",
	// "ModelRegistryService_deleteRegisteredModelAlias",
	// "ModelRegistryService_getModelVersionByAlias",
	// "MlflowArtifactsService_downloadArtifact",
	// "MlflowArtifactsService_uploadArtifact",
	// "MlflowArtifactsService_listArtifacts",
	// "MlflowArtifactsService_deleteArtifact",
	// "MlflowArtifactsService_createMultipartUpload",
	// "MlflowArtifactsService_completeMultipartUpload",
	// "MlflowArtifactsService_abortMultipartUpload",
}
