// Code generated by mlflow/go/tools/generate/main.go. DO NOT EDIT.

package routes

import (
	"github.com/gofiber/fiber/v2"
	"github.com/mlflow/mlflow/mlflow/go/pkg/server/parser"
	"github.com/mlflow/mlflow/mlflow/go/pkg/contract/service"
)

func RegisterModelRegistryServiceRoutes(service service.ModelRegistryService, parser *parser.HTTPRequestParser, app *fiber.App) {
}
