// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAlembicVersion = "alembic_version"

// AlembicVersion mapped from table <alembic_version>
type AlembicVersion struct {
	VersionNum string `gorm:"column:version_num;primaryKey" json:"version_num"`
}

// TableName AlembicVersion's table name
func (*AlembicVersion) TableName() string {
	return TableNameAlembicVersion
}
