// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameInput = "inputs"

// Input mapped from table <inputs>
type Input struct {
	InputUUID       string `gorm:"column:input_uuid;not null" json:"input_uuid"`
	SourceType      string `gorm:"column:source_type;primaryKey" json:"source_type"`
	SourceID        string `gorm:"column:source_id;primaryKey" json:"source_id"`
	DestinationType string `gorm:"column:destination_type;primaryKey" json:"destination_type"`
	DestinationID   string `gorm:"column:destination_id;primaryKey" json:"destination_id"`
}

// TableName Input's table name
func (*Input) TableName() string {
	return TableNameInput
}
