// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameLatestMetric = "latest_metrics"

// LatestMetric mapped from table <latest_metrics>
type LatestMetric struct {
	Key       string  `gorm:"column:key;primaryKey" json:"key"`
	Value     float64 `gorm:"column:value;not null" json:"value"`
	Timestamp int64   `gorm:"column:timestamp" json:"timestamp"`
	Step      int64   `gorm:"column:step;not null" json:"step"`
	IsNan     bool    `gorm:"column:is_nan;not null" json:"is_nan"`
	RunUUID   string  `gorm:"column:run_uuid;primaryKey" json:"run_uuid"`
}

// TableName LatestMetric's table name
func (*LatestMetric) TableName() string {
	return TableNameLatestMetric
}
