// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMetric = "metrics"

// Metric mapped from table <metrics>
type Metric struct {
	Key       string  `db:"key" gorm:"column:key;primaryKey" json:"key"`
	Value     float64 `db:"value" gorm:"column:value;primaryKey" json:"value"`
	Timestamp int64   `db:"timestamp" gorm:"column:timestamp;primaryKey" json:"timestamp"`
	RunUUID   string  `db:"run_uuid" gorm:"column:run_uuid;primaryKey" json:"run_uuid"`
	Step      int64   `db:"step" gorm:"column:step;primaryKey" json:"step"`
	IsNan     bool    `db:"is_nan" gorm:"column:is_nan;primaryKey" json:"is_nan"`
}

// TableName Metric's table name
func (*Metric) TableName() string {
	return TableNameMetric
}
