// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameModelVersionTag = "model_version_tags"

// ModelVersionTag mapped from table <model_version_tags>
type ModelVersionTag struct {
	Key     string `gorm:"column:key;primaryKey" json:"key"`
	Value   string `gorm:"column:value" json:"value"`
	Name    string `gorm:"column:name;primaryKey" json:"name"`
	Version int32  `gorm:"column:version;primaryKey" json:"version"`
}

// TableName ModelVersionTag's table name
func (*ModelVersionTag) TableName() string {
	return TableNameModelVersionTag
}
