// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameModelVersion = "model_versions"

// ModelVersion mapped from table <model_versions>
type ModelVersion struct {
	Name            string `gorm:"column:name;primaryKey" json:"name"`
	Version         int32  `gorm:"column:version;primaryKey" json:"version"`
	CreationTime    int64  `gorm:"column:creation_time" json:"creation_time"`
	LastUpdatedTime int64  `gorm:"column:last_updated_time" json:"last_updated_time"`
	Description     string `gorm:"column:description" json:"description"`
	UserID          string `gorm:"column:user_id" json:"user_id"`
	CurrentStage    string `gorm:"column:current_stage" json:"current_stage"`
	Source          string `gorm:"column:source" json:"source"`
	RunID           string `gorm:"column:run_id" json:"run_id"`
	Status          string `gorm:"column:status" json:"status"`
	StatusMessage   string `gorm:"column:status_message" json:"status_message"`
	RunLink         string `gorm:"column:run_link" json:"run_link"`
	StorageLocation string `gorm:"column:storage_location" json:"storage_location"`
}

// TableName ModelVersion's table name
func (*ModelVersion) TableName() string {
	return TableNameModelVersion
}
