// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameParam = "params"

// Param mapped from table <params>
type Param struct {
	Key     string `gorm:"column:key;primaryKey" json:"key"`
	Value   string `gorm:"column:value;not null" json:"value"`
	RunUUID string `gorm:"column:run_uuid;primaryKey" json:"run_uuid"`
}

// TableName Param's table name
func (*Param) TableName() string {
	return TableNameParam
}
