// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRegisteredModelAlias = "registered_model_aliases"

// RegisteredModelAlias mapped from table <registered_model_aliases>
type RegisteredModelAlias struct {
	Alias_  string `gorm:"column:alias;primaryKey" json:"alias"`
	Version int32  `gorm:"column:version;not null" json:"version"`
	Name    string `gorm:"column:name;primaryKey" json:"name"`
}

// TableName RegisteredModelAlias's table name
func (*RegisteredModelAlias) TableName() string {
	return TableNameRegisteredModelAlias
}
