// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRegisteredModelTag = "registered_model_tags"

// RegisteredModelTag mapped from table <registered_model_tags>
type RegisteredModelTag struct {
	Key   string `gorm:"column:key;primaryKey" json:"key"`
	Value string `gorm:"column:value" json:"value"`
	Name  string `gorm:"column:name;primaryKey" json:"name"`
}

// TableName RegisteredModelTag's table name
func (*RegisteredModelTag) TableName() string {
	return TableNameRegisteredModelTag
}
