// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRun = "runs"

// Run mapped from table <runs>
type Run struct {
	RunUUID        string `gorm:"column:run_uuid;primaryKey" json:"run_uuid"`
	Name           string `gorm:"column:name" json:"name"`
	SourceType     string `gorm:"column:source_type" json:"source_type"`
	SourceName     string `gorm:"column:source_name" json:"source_name"`
	EntryPointName string `gorm:"column:entry_point_name" json:"entry_point_name"`
	UserID         string `gorm:"column:user_id" json:"user_id"`
	Status         string `gorm:"column:status" json:"status"`
	StartTime      int64  `gorm:"column:start_time" json:"start_time"`
	EndTime        int64  `gorm:"column:end_time" json:"end_time"`
	SourceVersion  string `gorm:"column:source_version" json:"source_version"`
	LifecycleStage string `gorm:"column:lifecycle_stage" json:"lifecycle_stage"`
	ArtifactURI    string `gorm:"column:artifact_uri" json:"artifact_uri"`
	ExperimentID   int32  `gorm:"column:experiment_id" json:"experiment_id"`
	DeletedTime    int64  `gorm:"column:deleted_time" json:"deleted_time"`
}

// TableName Run's table name
func (*Run) TableName() string {
	return TableNameRun
}
