// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTag = "tags"

// Tag mapped from table <tags>
type Tag struct {
	Key     string `gorm:"column:key;primaryKey" json:"key"`
	Value   string `gorm:"column:value" json:"value"`
	RunUUID string `gorm:"column:run_uuid;primaryKey" json:"run_uuid"`
}

// TableName Tag's table name
func (*Tag) TableName() string {
	return TableNameTag
}
