services:
  mlflow:
    image: "ghcr.io/mlflow/mlflow-devcontainer"
    working_dir: /workspaces/mlflow
    environment:
      MLFLOW_HOME: /workspaces/mlflow
      MLFLOW_TRACKING_URI: sqlite:////workspaces/mlflow/mlruns.db
    volumes:
      - ..:/workspaces/mlflow:cached
      - build:/workspaces/mlflow/mlflow/server/js/build
      - gomodcache:/go/pkg/mod
    network_mode: service:db

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
  build:
  gomodcache:
  postgres-data:
